#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb  6 16:35:00 2018

@author: nsage
"""

from IsGraphic import is_graphic

def degree_sequence_info(l):
    deg = sum(l)
    if is_graphic(l) == False:
        print("Degree sequence is not graphic. Proceed with caution.")
    print("Vertices: ", len(l))
    print("Edges: ", int(deg/2))
    print("Degrees: ", deg)
    
degree_sequence_info([5,4,4,3,3,2,2,2,2,1,1])